### ISSUE TITLE
Unngå å sende innloggingsinfo i klartekst

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-backend#104]

**Comment by madsop** [comment]
Denne treng ein koordinert innsats mellom frontend og backend.

**Comment by zrrrzzt** [comment]
Enkleste er vel å bli enige om en algoritme og nøkkel for kryptering og så bruke den?

**Comment by madsop** [comment]
Sant.

Treng kanskje ikkje å bli einige om nøkkel eingong, viss både frontend og backend hentar den frå Secret Manager.

**Comment by zrrrzzt** [comment]
Secret Manager binder veldig opp til leverandør da og det kunne jeg tenke meg å unngå.
Vercel har en veldig bra greie med krypterte secrets som likevel kan hentes inn i miljøvariablene, finnes det noe tilsvarende på GCP?

**Comment by madsop** [comment]
Trur ikkje eg synes koplinga mot leverandør er så farleg, så lengje vi lager eit abstraksjonslag som er enkelt å bytte ut.

Særleg når backenden allereie bruker Secret Manager, og det gir oss moglegheit til å bruke samme secret frå både frontend og backend.

**Comment by madsop** [comment]
Ser ut som AES er den vanlegaste algoritmen ute og går, så da kan vi jo satse på den.
