### ISSUE TITLE
Sms-fallback e.l.

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-backend#114]
Om nokon ikkje tar telefonen tre (feks) gongar, send dei ein sms til dei

**Comment by madsop** [comment]
Dette er kanskje ein nice-to-have-feature, men vi må nok forvente at det er ein del som ikkje tar telefonen.

**Comment by zrrrzzt** [comment]
Selv sende sms er en enkel sak å sette opp i Twilio så man kunne i teorien gjort det mulig å sende sms til personer fra ringesiden og bare postet det som en oppføring på historikken til brukeren.
Avsendernummer da bør kanskje være det samme som det som mottar samtaler.

Men, vi er vel nå mer på crm enn ringesentral ;-)

**Comment by zrrrzzt** [comment]
Glem det...

Nummeret som er satt opp til å ringe fra har kun støtte for voice og fax (for realz) så vi kan ikke sende sms med det

**Comment by madsop** [comment]
> Glem det...
> 
> Nummeret som er satt opp til å ringe fra har kun støtte for voice og fax (for realz) så vi kan ikke sende sms med det

Det kan sikkert fiksast. Men er vel lurt å også tenkje behov her.

**Comment by zrrrzzt** [comment]
Nå har vi alt på stell så da er det mer å gruble seg frem til hvordan den skal kunne brukes.

**Comment by madsop** [comment]
Vi har allereie logikk (arva frå forrige runde) som seier at viss resultatet for denne samtalen er _ikke svar_, og vedkommande ikkje har svart tidlegare heller, og dette er tredje gongen vi prøver, så gir vi opp og sett personen som ferdigringt. Ei moglegheit er å hekte denne på den logikken.
