### ISSUE TITLE
servicebruker

### ISSUE THREAD

**Issue by zrrrzzt** [Roedt/ringesentralen-backend#132]
For at Twilio-boten skal kunne gjøre oppslag på hvem som ringer tilbake må den kunne opprette sitt eget token.

Dette skal benyttes til å slå opp på brukers telefonnummer og til å poste samtaleresultat når brukeren har gjort sitt valg.

**Comment by madsop** [comment]
Vurdering her om vi skal leggje til denne brukaren manuelt i Hypersys eller lage ei spesialløysing i vår backend.

**Comment by zrrrzzt** [comment]
Sånn umiddelbart tenker jeg kanskje at denne brukeren _ikke_ burde ligge i HS fordi den er veldig spesifikk for vår løsning.

**Comment by madsop** [comment]
Løyst i #138
