### ISSUE TITLE
Plan for uthenting av dataa

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-backend#136]
For så vidt både frå v1 og v2?

Skal vi poste tilbake til Hypersys eller manuelt hente ut frå databasen?

**Comment by KristofferLer** [comment]
Vi kan sette opp dynamiske felt i Hypersys. Som markers ja eller nei. Kan vi koble det med API?

Dette må jo da bli mot allerede medlemmer. Mot velgere må vi vel ha en manuelt oppfølging.

-F.eks
- vil ha valgkampbrev , Ja/nei
- Vil bli mer aktiv Rødt ja/nei

Skal jeg lage disse feltene?

**Comment by madsop** [comment]
Vi får vurdere det litt. Per no skriv vi ingenting til Hypersys, og det er litt tryggleik i å ikkje gjera det.
