### ISSUE TITLE
Abstraksjonslag foran GCP Secret Manager

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-backend#139]

**Comment by zrrrzzt** [comment]
Kan vi ikke bare løse det i builden? https://cloud.google.com/build/docs/securing-builds/use-secrets
Henter secrets fra manager og legger det inn som miljøvariabler. Da er vi så løsrevet vi kan bli :-)

**Comment by madsop** [comment]
> Kan vi ikke bare løse det i builden? https://cloud.google.com/build/docs/securing-builds/use-secrets
> Henter secrets fra manager og legger det inn som miljøvariabler. Da er vi så løsrevet vi kan bli :-)

Jo, det høyrast ut som ei veldig god løysing. Krev litt tilpassing for utvikling lokalt, men det er fair.

**Comment by zrrrzzt** [comment]
På frontend slipper vi unna med en .env lokalt, mulig det er litt mer pes for lokal backend?
