### ISSUE TITLE
Manuelt innlagte/prioriterte nummer?

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-backend#150]
Om vi vil køyre ein "vurderer du å stemme Raudt? vil du snakke med ein av våre aktivistar? skriv deg opp her, så ringer vi deg"-aktig kampanje.

**Comment by madsop** [comment]
Frå Geir: Kan jo gjøre det utrolig enkelt vha f.eks. Twilio.
Registrer navn, adresse og nr her. Så sender vi link til nummeret slik at de må bekrefte at det faktisk er de selv som har lagt seg inn så legges de til på Ringesentralen

**Comment by KristofferLer** [comment]
Herlig! Så baker vi den inn på nettsiden?

**Comment by madsop** [comment]
Frå backend treng vi her litt info om denne personen:
- fornamn
- etternamn
- telefonnummer
- postnummer

Og da eit endepunkt a la POST /person/skalRinges e.l, som tar inn lista over som request-objekt.

Kanskje vi også bør markere desse på eit vis, at dei sjølv har registrert seg/vorte verva.

Og så justere mekanikken for å hente neste veljar å ringe sånn at denne hamnar først.

**Comment by zrrrzzt** [comment]
Vi trenger et sms-nummer for Twilio. Utover det er det som vanlig bare et par web-hooks som skal til.
Tenker vel det er greit å dele i 2 endepunkt? Ett for å ta imot info og ett for å ta imot henvendelser fra Twilio.
Det siste kan jeg fint legge inn under /api/twilio på frontend.

Er det tenkt at man skal kunne verve også fra ringesentralen, eller er dette kun fra vanlige websiden?

**Comment by madsop** [comment]
Frå det tekniske perspektivet vil eg helst ha det i Ringesentralen (dog tilgjengeleg utan innlogging), for å ikkje ha fleire frontendar som koplar seg opp mot backenden.

**Comment by zrrrzzt** [comment]
Ok, så en ringesentralen/verving da som er et slikt skjema?
Dette poster til backend som trigger en sms og så ligger håndtering av sms (lese den) i front som så poster en boost dette nummeret melding til backend?

**Comment by madsop** [comment]
Ja, noko sånt. Lurer på om trigginga av sms-en også bør skje i frontenden, sia all annan Twilio-integrasjon er derifrå?

**Comment by madsop** [comment]
Backenden for dette er på plass, så lukkkar denne. Får melde bugs ved behov.
