### ISSUE TITLE
Støtte å ringe veljarar frå definerte andre lokallag i samme fylke

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-backend#194]
Dvs støtte for https://github.com/Roedt/ringesentralen-frontend/issues/148

- Ønska lokallag som parameter i /samtale/neste
- Teneste for å hente ut alle tilgjengelege lokallag for innlogga brukar

**Comment by zrrrzzt** [comment]
Vil da trenge lokallagID som en av responsene på `/profil` om vi tar det non-breaking eller `lokallag: { navn, id }` om vi skal skape unødige avhengigheter ;-)

**Comment by zrrrzzt** [comment]
glem det, ser ut til at lokallag faktisk er id her :-)
